[package]
name = "deno-rusty-markdown"
version = "0.1.0"
authors = ["Sr Komodo <komodosr@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"
pulldown-cmark = "0.7.2"
