[package]
name = "deno_rusty_markdown"
version = "0.2.0"
authors = ["Sr Komodo <komodosr@gmail.com>"]
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"
pulldown-cmark = "0.8.0"

[profile.release]
opt-level = "s"
lto = true
