name: "Setup Environment"
description: "Sets up the environment"
inputs:
  rust-version:
    description: "Wich Rust version to use"
    required: true
    default: "stable"
  deno-version:
    description: "Wich Deno version to use"
    required: true
    default: "v1.x"
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        target: wasm32-unknown-unknown
        profile: minimal
        override: true
    - name: Setup Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}
