name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        rust: ["stable", "nightly"]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Setup wasm-bindgen
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-bindgen-cli
          version: 0.2.67
          use-tool-cache: true
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run Rust tests
        run: cargo test
      - name: Build WebAssembly
        run: deno run --allow-read --allow-write --allow-run ./build.ts
      - name: Run Deno tests
        run: deno test
