name: Make sure WASM output is up to date

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Setup wasm-bindgen
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-bindgen-cli
          version: 0.2.67
          use-tool-cache: true
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Check if WASM output is up to date
        run: scripts/compare_checksums.sh
